apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: {{ .Values.service.postgresqlPort }}
      targetPort: 5432
