apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8200
