apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Must match vault-pvc's storage class
  hostPath:
    path: "/mnt/data/vault"  # Make sure this directory exists on worker nodes
