apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Must match PVC's storage class
  hostPath:
    path: "/mnt/data/vault"  # Ensure this path exists on worker nodes
